from collections import namedtuple

Genotype = namedtuple('Genotype', 'alpha_cell concat_node')
 
ZINC_Net    = [Genotype(alpha_cell=[('f_identity', 1, 0), ('f_dense', 2, 0), ('f_identity', 3, 1), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_dense', 7, 5), ('f_identity', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_identity', 1, 0), ('f_identity', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 1), ('a_max', 4, 1), ('a_max', 5, 2), ('f_sparse', 6, 5), ('f_sparse', 7, 6), ('f_sparse', 8, 7)], concat_node=None)]

MNIST_Net   = [Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_dense', 2, 1), ('f_sparse', 3, 2), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 6), ('f_identity', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_dense', 3, 0), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_identity', 7, 5), ('f_identity', 8, 6), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 0), ('f_sparse', 3, 0), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 4), ('f_dense', 8, 4), ('f_sparse', 9, 6)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_sparse', 3, 2), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 6), ('f_sparse', 9, 8)], concat_node=None)]

CIFAR10_Net = [Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_dense', 2, 1), ('f_sparse', 3, 2), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 6), ('f_identity', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_dense', 3, 0), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_identity', 7, 5), ('f_identity', 8, 6), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 0), ('f_sparse', 3, 0), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 4), ('f_dense', 8, 4), ('f_sparse', 9, 6)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_sparse', 3, 2), ('a_max', 4, 1), ('a_max', 5, 2), ('a_max', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 6), ('f_sparse', 9, 8)], concat_node=None)]

PATTERN_Net = [Genotype(alpha_cell=[('f_identity', 1, 0), ('f_dense', 2, 0), ('f_identity', 3, 1), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_dense', 7, 5), ('f_identity', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_identity', 1, 0), ('f_identity', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 1), ('a_max', 4, 1), ('a_max', 5, 2), ('f_sparse', 6, 5), ('f_sparse', 7, 6), ('f_sparse', 8, 7)], concat_node=None)]

CLUSTER_Net = [Genotype(alpha_cell=[('f_identity', 1, 0), ('f_dense', 2, 0), ('f_identity', 3, 1), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_dense', 7, 5), ('f_identity', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_identity', 1, 0), ('f_identity', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 0), ('a_sum', 4, 1), ('a_sum', 5, 2), ('a_sum', 6, 3), ('f_sparse', 7, 4), ('f_sparse', 8, 7), ('f_sparse', 9, 8)], concat_node=None), Genotype(alpha_cell=[('f_sparse', 1, 0), ('f_sparse', 2, 1), ('f_identity', 3, 1), ('a_max', 4, 1), ('a_max', 5, 2), ('f_sparse', 6, 5), ('f_sparse', 7, 6), ('f_sparse', 8, 7)], concat_node=None)]



